import React from "react";

export interface Props {}

const SVG: React.SFC<Props> = () => {
    return (
        <>
            <svg className="Rectangle_13">
                <rect
                    id="Rectangle_13"
                    rx={0}
                    ry={0}
                    x={0}
                    y={0}
                    width={1920}
                    height={350}
                ></rect>
            </svg>
            <div id="ID234">
                <div id="Layer_3">
                    <svg className="Rectangle_223">
                        <rect
                            id="Rectangle_223"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="182.666"
                            height="252.351"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_224">
                        <rect
                            id="Rectangle_224"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="152.703"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_225">
                        <rect
                            id="Rectangle_225"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="152.703"
                            height="152.703"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_226">
                        <rect
                            id="Rectangle_226"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="101.799"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_227">
                        <rect
                            id="Rectangle_227"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_228">
                        <rect
                            id="Rectangle_228"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_229">
                        <rect
                            id="Rectangle_229"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="203.598"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_230">
                        <rect
                            id="Rectangle_230"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="203.598"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_231">
                        <rect
                            id="Rectangle_231"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="203.598"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_232">
                        <rect
                            id="Rectangle_232"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_233">
                        <rect
                            id="Rectangle_233"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_234">
                        <rect
                            id="Rectangle_234"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="152.703"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_235">
                        <rect
                            id="Rectangle_235"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_236">
                        <rect
                            id="Rectangle_236"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_237">
                        <rect
                            id="Rectangle_237"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_238">
                        <rect
                            id="Rectangle_238"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_239">
                        <rect
                            id="Rectangle_239"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_240">
                        <rect
                            id="Rectangle_240"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_241">
                        <rect
                            id="Rectangle_241"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="152.703"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_242">
                        <rect
                            id="Rectangle_242"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="152.703"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_243">
                        <rect
                            id="Rectangle_243"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="152.703"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_244">
                        <rect
                            id="Rectangle_244"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_245">
                        <rect
                            id="Rectangle_245"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_246">
                        <rect
                            id="Rectangle_246"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_247">
                        <rect
                            id="Rectangle_247"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_248">
                        <rect
                            id="Rectangle_248"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_249">
                        <rect
                            id="Rectangle_249"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_250">
                        <rect
                            id="Rectangle_250"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_251">
                        <rect
                            id="Rectangle_251"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_252">
                        <rect
                            id="Rectangle_252"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_253">
                        <rect
                            id="Rectangle_253"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_254">
                        <rect
                            id="Rectangle_254"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_255">
                        <rect
                            id="Rectangle_255"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_256">
                        <rect
                            id="Rectangle_256"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_257">
                        <rect
                            id="Rectangle_257"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_258">
                        <rect
                            id="Rectangle_258"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_259">
                        <rect
                            id="Rectangle_259"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_260">
                        <rect
                            id="Rectangle_260"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_261">
                        <rect
                            id="Rectangle_261"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_262">
                        <rect
                            id="Rectangle_262"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_263">
                        <rect
                            id="Rectangle_263"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_264">
                        <rect
                            id="Rectangle_264"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_265">
                        <rect
                            id="Rectangle_265"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_266">
                        <rect
                            id="Rectangle_266"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_267">
                        <rect
                            id="Rectangle_267"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_268">
                        <rect
                            id="Rectangle_268"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_269">
                        <rect
                            id="Rectangle_269"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_270">
                        <rect
                            id="Rectangle_270"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_271">
                        <rect
                            id="Rectangle_271"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_272">
                        <rect
                            id="Rectangle_272"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_273">
                        <rect
                            id="Rectangle_273"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_274">
                        <rect
                            id="Rectangle_274"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_275">
                        <rect
                            id="Rectangle_275"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_276">
                        <rect
                            id="Rectangle_276"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_277">
                        <rect
                            id="Rectangle_277"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_278">
                        <rect
                            id="Rectangle_278"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_279">
                        <rect
                            id="Rectangle_279"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_280">
                        <rect
                            id="Rectangle_280"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_281">
                        <rect
                            id="Rectangle_281"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_282">
                        <rect
                            id="Rectangle_282"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_283">
                        <rect
                            id="Rectangle_283"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_284">
                        <rect
                            id="Rectangle_284"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_285">
                        <rect
                            id="Rectangle_285"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_286">
                        <rect
                            id="Rectangle_286"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="101.799"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_287">
                        <rect
                            id="Rectangle_287"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_288">
                        <rect
                            id="Rectangle_288"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_289">
                        <rect
                            id="Rectangle_289"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_290">
                        <rect
                            id="Rectangle_290"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_291">
                        <rect
                            id="Rectangle_291"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_292">
                        <rect
                            id="Rectangle_292"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_293">
                        <rect
                            id="Rectangle_293"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_294">
                        <rect
                            id="Rectangle_294"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="101.799"
                            height="101.799"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_295">
                        <rect
                            id="Rectangle_295"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_296">
                        <rect
                            id="Rectangle_296"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_297">
                        <rect
                            id="Rectangle_297"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_298">
                        <rect
                            id="Rectangle_298"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_299">
                        <rect
                            id="Rectangle_299"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_300">
                        <rect
                            id="Rectangle_300"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_301">
                        <rect
                            id="Rectangle_301"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_302">
                        <rect
                            id="Rectangle_302"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="203.598"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_303">
                        <rect
                            id="Rectangle_303"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_304">
                        <rect
                            id="Rectangle_304"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_305">
                        <rect
                            id="Rectangle_305"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_306">
                        <rect
                            id="Rectangle_306"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_307">
                        <rect
                            id="Rectangle_307"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_308">
                        <rect
                            id="Rectangle_308"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_309">
                        <rect
                            id="Rectangle_309"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_310">
                        <rect
                            id="Rectangle_310"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_311">
                        <rect
                            id="Rectangle_311"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="50.904"
                            height="50.904"
                        ></rect>
                    </svg>
                </div>
                <div id="Layer_2">
                    <svg className="Rectangle_312">
                        <rect
                            id="Rectangle_312"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="151.149"
                            height="180.808"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_313">
                        <rect
                            id="Rectangle_313"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_314">
                        <rect
                            id="Rectangle_314"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="302.705"
                            height="179.7"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_315">
                        <rect
                            id="Rectangle_315"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="241.984"
                            height="34.454"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_316">
                        <rect
                            id="Rectangle_316"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="181.093"
                            height="36.747"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_317">
                        <rect
                            id="Rectangle_317"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="91.082"
                            height="30.199"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_318">
                        <rect
                            id="Rectangle_318"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_319">
                        <rect
                            id="Rectangle_319"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="150.467"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_320">
                        <rect
                            id="Rectangle_320"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="89.831"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_321">
                        <rect
                            id="Rectangle_321"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="59.878"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_322">
                        <rect
                            id="Rectangle_322"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="31.062"
                            height="29.953"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_323">
                        <rect
                            id="Rectangle_323"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_324">
                        <rect
                            id="Rectangle_324"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_325">
                        <rect
                            id="Rectangle_325"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_326">
                        <rect
                            id="Rectangle_326"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_327">
                        <rect
                            id="Rectangle_327"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_328">
                        <rect
                            id="Rectangle_328"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_329">
                        <rect
                            id="Rectangle_329"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_330">
                        <rect
                            id="Rectangle_330"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_331">
                        <rect
                            id="Rectangle_331"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_332">
                        <rect
                            id="Rectangle_332"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_333">
                        <rect
                            id="Rectangle_333"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_334">
                        <rect
                            id="Rectangle_334"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_335">
                        <rect
                            id="Rectangle_335"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_336">
                        <rect
                            id="Rectangle_336"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_337">
                        <rect
                            id="Rectangle_337"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_338">
                        <rect
                            id="Rectangle_338"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_339">
                        <rect
                            id="Rectangle_339"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_340">
                        <rect
                            id="Rectangle_340"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_341">
                        <rect
                            id="Rectangle_341"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_342">
                        <rect
                            id="Rectangle_342"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_343">
                        <rect
                            id="Rectangle_343"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_344">
                        <rect
                            id="Rectangle_344"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_345">
                        <rect
                            id="Rectangle_345"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_346">
                        <rect
                            id="Rectangle_346"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_347">
                        <rect
                            id="Rectangle_347"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_348">
                        <rect
                            id="Rectangle_348"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_349">
                        <rect
                            id="Rectangle_349"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_350">
                        <rect
                            id="Rectangle_350"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_351">
                        <rect
                            id="Rectangle_351"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_352">
                        <rect
                            id="Rectangle_352"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_353">
                        <rect
                            id="Rectangle_353"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_354">
                        <rect
                            id="Rectangle_354"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_355">
                        <rect
                            id="Rectangle_355"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_356">
                        <rect
                            id="Rectangle_356"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_357">
                        <rect
                            id="Rectangle_357"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_358">
                        <rect
                            id="Rectangle_358"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_359">
                        <rect
                            id="Rectangle_359"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_360">
                        <rect
                            id="Rectangle_360"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_361">
                        <rect
                            id="Rectangle_361"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_362">
                        <rect
                            id="Rectangle_362"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_363">
                        <rect
                            id="Rectangle_363"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_364">
                        <rect
                            id="Rectangle_364"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_365">
                        <rect
                            id="Rectangle_365"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_366">
                        <rect
                            id="Rectangle_366"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_367">
                        <rect
                            id="Rectangle_367"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_368">
                        <rect
                            id="Rectangle_368"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_369">
                        <rect
                            id="Rectangle_369"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_370">
                        <rect
                            id="Rectangle_370"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_371">
                        <rect
                            id="Rectangle_371"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_372">
                        <rect
                            id="Rectangle_372"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_373">
                        <rect
                            id="Rectangle_373"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_374">
                        <rect
                            id="Rectangle_374"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_375">
                        <rect
                            id="Rectangle_375"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="151.083"
                            height="149.604"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_376">
                        <rect
                            id="Rectangle_376"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_377">
                        <rect
                            id="Rectangle_377"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="150.476"
                            height="89.66"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_378">
                        <rect
                            id="Rectangle_378"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_379">
                        <rect
                            id="Rectangle_379"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_380">
                        <rect
                            id="Rectangle_380"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_381">
                        <rect
                            id="Rectangle_381"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_382">
                        <rect
                            id="Rectangle_382"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_383">
                        <rect
                            id="Rectangle_383"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_384">
                        <rect
                            id="Rectangle_384"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="81.132"
                            height="30.057"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_385">
                        <rect
                            id="Rectangle_385"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_386">
                        <rect
                            id="Rectangle_386"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_387">
                        <rect
                            id="Rectangle_387"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_388">
                        <rect
                            id="Rectangle_388"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_389">
                        <rect
                            id="Rectangle_389"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_390">
                        <rect
                            id="Rectangle_390"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_391">
                        <rect
                            id="Rectangle_391"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_392">
                        <rect
                            id="Rectangle_392"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_393">
                        <rect
                            id="Rectangle_393"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_394">
                        <rect
                            id="Rectangle_394"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_395">
                        <rect
                            id="Rectangle_395"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_396">
                        <rect
                            id="Rectangle_396"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_397">
                        <rect
                            id="Rectangle_397"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_398">
                        <rect
                            id="Rectangle_398"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_399">
                        <rect
                            id="Rectangle_399"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_400">
                        <rect
                            id="Rectangle_400"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_401">
                        <rect
                            id="Rectangle_401"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_402">
                        <rect
                            id="Rectangle_402"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_403">
                        <rect
                            id="Rectangle_403"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_404">
                        <rect
                            id="Rectangle_404"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_405">
                        <rect
                            id="Rectangle_405"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_406">
                        <rect
                            id="Rectangle_406"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_407">
                        <rect
                            id="Rectangle_407"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_408">
                        <rect
                            id="Rectangle_408"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_409">
                        <rect
                            id="Rectangle_409"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_410">
                        <rect
                            id="Rectangle_410"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_411">
                        <rect
                            id="Rectangle_411"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_412">
                        <rect
                            id="Rectangle_412"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_413">
                        <rect
                            id="Rectangle_413"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_414">
                        <rect
                            id="Rectangle_414"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_415">
                        <rect
                            id="Rectangle_415"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_416">
                        <rect
                            id="Rectangle_416"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_417">
                        <rect
                            id="Rectangle_417"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_418">
                        <rect
                            id="Rectangle_418"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_419">
                        <rect
                            id="Rectangle_419"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_420">
                        <rect
                            id="Rectangle_420"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_421">
                        <rect
                            id="Rectangle_421"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_422">
                        <rect
                            id="Rectangle_422"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_423">
                        <rect
                            id="Rectangle_423"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_424">
                        <rect
                            id="Rectangle_424"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_425">
                        <rect
                            id="Rectangle_425"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_426">
                        <rect
                            id="Rectangle_426"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_427">
                        <rect
                            id="Rectangle_427"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_428">
                        <rect
                            id="Rectangle_428"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_429">
                        <rect
                            id="Rectangle_429"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_430">
                        <rect
                            id="Rectangle_430"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                    <svg className="Rectangle_431">
                        <rect
                            id="Rectangle_431"
                            rx={0}
                            ry={0}
                            x={0}
                            y={0}
                            width="30.133"
                            height="30.133"
                        ></rect>
                    </svg>
                </div>
            </div>
            <div id="BLACK_MIRROR">
                <span>BLACK MIRROR</span>
            </div>
            <svg className="Rectangle_440">
                <rect
                    id="Rectangle_440"
                    rx={40}
                    ry={40}
                    x={0}
                    y={0}
                    width={260}
                    height={97}
                ></rect>
            </svg>
        </>
    );
};

export default SVG;
