const styles = {
  '.mediaViewInfo': {
    '-WebViewName': 'HOST PROFILE',
    '-WebViewId': 'HOST_PROFILE',
    '-WebScaleOnResize': 'true',
    '-WebEnableDeepLinking': 'true',
  },
  ',\n\t:root': {'-WebViewIds': 'HOST_PROFILE'},
  ',\n\t*': {
    margin: '0',
    padding: '0',
    boxSizing: 'border-box',
    border: 'none',
  },
  ',\n\t#HOST_PROFILE': {
    position: 'absolute',
    width: '375',
    height: '812',
    background:
      'linear-gradient(165.4deg, rgba(32,15,70,1) 0%, rgba(51,68,131,1) 100%)',
    overflow: 'hidden',
    '-WebViewName': 'HOST PROFILE',
    '-WebViewId': 'HOST_PROFILE',
    '-WebScaleOnResize': 'true',
    '-WebEnableDeepLinking': 'true',
  },
  '@keyframes fadein': {'0%': {opacity: '0'}, '100%': {opacity: '1'}},
  '#PROFILE': {
    left: '25',
    top: '60',
    position: 'absolute',
    overflow: 'visible',
    width: '246',
    whiteSpace: 'nowrap',
    lineHeight: '40',
    marginTop: '-2.5',
    textAlign: 'center',
    fontFamily: 'Press Start 2P',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '35',
    color: 'rgba(91,191,227,1)',
  },
  '#GENDER': {
    left: '48',
    top: '126',
    position: 'absolute',
    overflow: 'visible',
    width: '66',
    whiteSpace: 'nowrap',
    lineHeight: '120',
    marginTop: '-51.5',
    textAlign: 'left',
    fontFamily: 'Quantico',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '17',
    color: 'rgba(196,201,255,1)',
  },
  '#FINCIAL_EXPECTATIONS': {
    left: '48',
    top: '223',
    position: 'absolute',
    overflow: 'visible',
    width: '187',
    whiteSpace: 'nowrap',
    lineHeight: '120',
    marginTop: '-51.5',
    textAlign: 'left',
    fontFamily: 'Quantico',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '17',
    color: 'rgba(196,201,255,1)',
  },
  '#CARRER_HABITUTES': {
    left: '48',
    top: '329',
    position: 'absolute',
    overflow: 'visible',
    width: '161',
    whiteSpace: 'nowrap',
    lineHeight: '120',
    marginTop: '-51.5',
    textAlign: 'left',
    fontFamily: 'Quantico',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '17',
    color: 'rgba(196,201,255,1)',
  },
  '#Rectangle_1645': {fill: 'rgba(91,191,227,0.204)'},
  '.Rectangle_1645': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '51',
    top: '171',
  },
  '#Rectangle_1646': {
    fill: 'transparent',
    stroke: 'rgba(91,191,227,1)',
    strokeWidth: '3',
    strokeLinejoin: 'miter',
    strokeLinecap: 'butt',
    strokeMiterlimit: '4',
    shapeRendering: 'auto',
  },
  '.Rectangle_1646': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '51',
    top: '170',
  },
  '#Rectangle_1647': {
    fill: 'transparent',
    stroke: 'rgba(91,191,227,1)',
    strokeWidth: '3',
    strokeLinejoin: 'miter',
    strokeLinecap: 'butt',
    strokeMiterlimit: '4',
    shapeRendering: 'auto',
  },
  '.Rectangle_1647': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '51',
    top: '170',
  },
  '#Polygon_5': {fill: 'rgba(91,191,227,1)'},
  '.Polygon_5': {
    overflow: 'hidden',
    position: 'absolute',
    width: '12',
    height: '7',
    transform: 'matrix(1,0,0,1,144,182) rotate(180deg)',
    transformOrigin: 'center',
    left: '0',
    top: '0',
  },
  '#Group_90': {
    position: 'absolute',
    width: '115',
    height: '31',
    left: '48',
    top: '269',
    overflow: 'visible',
  },
  '#Rectangle_1643': {fill: 'rgba(91,191,227,0.204)'},
  '.Rectangle_1643': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '0',
    top: '0',
  },
  '#Rectangle_1644': {
    fill: 'transparent',
    stroke: 'rgba(91,191,227,1)',
    strokeWidth: '3',
    strokeLinejoin: 'miter',
    strokeLinecap: 'butt',
    strokeMiterlimit: '4',
    shapeRendering: 'auto',
  },
  '.Rectangle_1644': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '0',
    top: '0',
  },
  '#Polygon_6': {fill: 'rgba(91,191,227,1)'},
  '.Polygon_6': {
    overflow: 'hidden',
    position: 'absolute',
    width: '12',
    height: '7',
    transform: 'translate(-70, -370) matrix(1,0,0,1,163,383) rotate(180deg)',
    transformOrigin: 'center',
    left: '0',
    top: '0',
  },
  '#Group_91': {
    position: 'absolute',
    width: '115',
    height: '31',
    left: '212',
    top: '267',
    overflow: 'visible',
  },
  '#Group_89': {
    position: 'absolute',
    width: '115',
    height: '31',
    left: '0',
    top: '0',
    overflow: 'visible',
  },
  '#Rectangle_1630': {fill: 'rgba(91,191,227,0.204)'},
  '.Rectangle_1630': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '0',
    top: '0',
  },
  '#Rectangle_1631': {
    fill: 'transparent',
    stroke: 'rgba(91,191,227,1)',
    strokeWidth: '3',
    strokeLinejoin: 'miter',
    strokeLinecap: 'butt',
    strokeMiterlimit: '4',
    shapeRendering: 'auto',
  },
  '.Rectangle_1631': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '0',
    top: '0',
  },
  '#Polygon_4': {fill: 'rgba(91,191,227,1)'},
  '.Polygon_4': {
    overflow: 'hidden',
    position: 'absolute',
    width: '13',
    height: '7',
    transform:
      'translate(0.295, 0.352) matrix(1,0,0,1,92.7046,12.6477) rotate(180deg)',
    transformOrigin: 'center',
    left: '0',
    top: '0',
  },
  '#TO': {
    left: '177',
    top: '271',
    position: 'absolute',
    overflow: 'visible',
    width: '23',
    whiteSpace: 'nowrap',
    lineHeight: '120',
    marginTop: '-51.5',
    textAlign: 'center',
    fontFamily: 'Quantico',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '17',
    color: 'rgba(196,201,255,1)',
  },
  '#Group_92': {
    position: 'absolute',
    width: '145.701',
    height: '32',
    left: '48',
    top: '374',
    overflow: 'visible',
  },
  '#plus': {
    position: 'absolute',
    width: '12.511',
    height: '12.511',
    left: '133.19',
    top: '9.366',
    overflow: 'visible',
  },
  '#Group_82': {
    position: 'absolute',
    width: '12.511',
    height: '12.511',
    left: '0',
    top: '0',
    overflow: 'visible',
  },
  '#Path_1165': {fill: 'rgba(91,191,227,1)'},
  '.Path_1165': {
    overflow: 'visible',
    position: 'absolute',
    width: '12.511',
    height: '12.511',
    left: '0',
    top: '0',
    transform: 'matrix(1,0,0,1,0,0)',
  },
  '#Polygon_7': {fill: 'rgba(91,191,227,1)'},
  '.Polygon_7': {
    overflow: 'hidden',
    position: 'absolute',
    width: '12',
    height: '7',
    transform: 'translate(-69, -544) matrix(1,0,0,1,162,556) rotate(180deg)',
    transformOrigin: 'center',
    left: '0',
    top: '0',
  },
  '#Rectangle_1648': {fill: 'rgba(91,191,227,0.204)'},
  '.Rectangle_1648': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '0',
    top: '1',
  },
  '#Rectangle_1649': {
    fill: 'transparent',
    stroke: 'rgba(91,191,227,1)',
    strokeWidth: '3',
    strokeLinejoin: 'miter',
    strokeLinecap: 'butt',
    strokeMiterlimit: '4',
    shapeRendering: 'auto',
  },
  '.Rectangle_1649': {
    position: 'absolute',
    overflow: 'visible',
    width: '115',
    height: '31',
    left: '0',
    top: '0',
  },
  '#Group_86': {
    position: 'absolute',
    width: '133',
    height: '56',
    left: '43',
    top: '546',
    overflow: 'visible',
    '-WebAnimation': 'fadein 0.3s ease-out',
    '-WebActionType': 'page',
    '-WebActionTarget': 'HOST.html',
    cursor: 'pointer',
  },
  '#Rectangle_1640': {
    fill: 'transparent',
    stroke: 'rgba(91,191,227,1)',
    strokeWidth: '8',
    strokeLinejoin: 'miter',
    strokeLinecap: 'butt',
    strokeMiterlimit: '4',
    shapeRendering: 'auto',
  },
  '.Rectangle_1640': {
    position: 'absolute',
    overflow: 'visible',
    width: '133',
    height: '56',
    left: '0',
    top: '0',
  },
  '#CREATE_ROLE': {
    left: '37',
    top: '8',
    position: 'absolute',
    overflow: 'visible',
    width: '61',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    fontFamily: 'Quantico',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '17',
    color: 'rgba(196,201,255,1)',
  },
  '#Group_166': {
    position: 'absolute',
    width: '133',
    height: '56',
    left: '199',
    top: '546',
    overflow: 'visible',
    '-WebAnimation': 'fadein 0.3s ease-out',
    '-WebActionType': 'page',
    '-WebActionTarget': 'HOST___2.html',
    cursor: 'pointer',
  },
  '#Rectangle_1640_b': {
    fill: 'transparent',
    stroke: 'rgba(91,191,227,1)',
    strokeWidth: '8',
    strokeLinejoin: 'miter',
    strokeLinecap: 'butt',
    strokeMiterlimit: '4',
    shapeRendering: 'auto',
  },
  '.Rectangle_1640_b': {
    position: 'absolute',
    overflow: 'visible',
    width: '133',
    height: '56',
    left: '0',
    top: '0',
  },
  '#CREATE_SCENARIO': {
    left: '25',
    top: '8',
    position: 'absolute',
    overflow: 'visible',
    width: '85',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    fontFamily: 'Quantico',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '17',
    color: 'rgba(196,201,255,1)',
  },
};

export default styles;
